version: 1.0.{build}
branches:
  only:
  - develop
  - master
os:
  - Visual Studio 2015
configuration:
  - Debug-2013
  - Release-2013
  - Debug-2015
  - Release-2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: "{version} ($(CONFIGURATION)/$(APPVEYOR_REPO_BRANCH))"
before_build:
  - if %CONFIGURATION%==Debug-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
  - if %CONFIGURATION%==Release-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
build:
  project: 'DummyConsoleApp1\DummyConsoleApp1.sln'
  verbosity: minimal
artifacts:
  - path: DummyConsoleApp1\bin\$(configuration)
    name: DummyConsoleApp1_$(APPVEYOR_REPO_BRANCH)_$(CONFIGURATION)