version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: false
os:
  - Visual Studio 2015
configuration:
#  - Debug-2013
#  - Release-2013
  - Debug-2015
  - Release-2015
before_build:
  - if %CONFIGURATION%==Debug-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
  - if %CONFIGURATION%==Release-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
build:
  project: 'DummyConsoleApp1\DummyConsoleApp1.sln'
  verbosity: minimal
after_build:
  - package.cmd "%APPVEYOR_PROJECT_NAME%-%GitVersion_SemVer%-%CONFIGURATION%-%GitVersion_BranchName%.zip" %APPVEYOR_BUILD_FOLDER% %CONFIGURATION%
artifacts:
  - path: '*.zip'
deploy:
    # Create new Release in GitHub
  - provider: GitHub
    auth_token:
      secure: 5Cf8pHC/OuSTy7igeFv11fuWqOQQ4PF+gDaWesmVVTs4kTjIGYWOrbBaViQ9vyrN
    artifact: /.*\.zip/
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
