version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: false
os:
  - Visual Studio 2015
configuration:
  - Debug-2013
  - Release-2013
  - Debug-2015
  - Release-2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: "{version} ($(CONFIGURATION)/$(APPVEYOR_REPO_BRANCH))"
before_build:
  - if %CONFIGURATION%==Debug-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
  - if %CONFIGURATION%==Release-2013 set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
build:
  project: 'DummyConsoleApp1\DummyConsoleApp1.sln'
  verbosity: minimal
after_build:
  - 7z a "%APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%.zip" %APPVEYOR_BUILD_FOLDER%\DummyConsoleApp1\bin\%CONFIGURATION%\* -r -x!Microsoft.* -x!System.* -x!Newtonsoft.*
artifacts:
  - path: '*.zip'
#    name: DummyConsoleApp1_$(APPVEYOR_REPO_BRANCH)_$(CONFIGURATION)
deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: 5Cf8pHC/OuSTy7igeFv11fuWqOQQ4PF+gDaWesmVVTs4kTjIGYWOrbBaViQ9vyrN
    artifact: /.*\.zip/
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
