name: call-gitversion

on: push

jobs:
  build:
    # If the action you're using is a Docker container you must run the job in a Linux virtual environment
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - name: Download GitVersion
      uses: docker://gittools/gitversion::latest-windows-netcoreapp2.2
      with:
        args: /updateassemblyinfo
    - run: Get-Content DummyConsoleApp1/Properties/AssemblyInfo.cs
      shell: pwsh
