name: test-conditions

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Always'
      run: 'echo "github.ref = ${{ github.ref }}"'
    - name: 'if tag'
      if: startsWith(github.ref, 'refs/tags/v')
      run: 'echo "tag"'
    - name: 'if master'
      if: github.ref == 'ref/head/master'
      run: 'echo "master"'
    - name: 'if tag or master'
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'ref/head/master'
      run: 'echo "tag or master"'
    - name: 'if master or tag'
      if: github.ref == 'ref/head/master' || startsWith(github.ref, 'refs/tags/v')
      run: 'echo "master or tag"'
    - name: 'if quoted tag or master'
      if: "startsWith(github.ref, 'refs/tags/v') || github.ref == 'ref/head/master'"
      run: 'echo "tag or master quoted"'
