on: push

jobs:
  build:
    # If the action you're using is a Docker container you must run the job in a Linux virtual environment
    runs-on: ubuntu-latest
    steps:
    - run: echo "$MY_SECRET_JSON" > data.json
      env:
        MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
    - run: Scripts/dump-data.sh
    - run: rm data.json
