on: push

jobs:
  build:
    # If the action you're using is a Docker container you must run the job in a Linux virtual environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "$MY_SECRET_JSON" > $GITHUB_WORKSPACE/data.json
      env:
        MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
    - run: Scripts/dumper.ps1 -datafile $env:GITHUB_WORKSPACE/data.json
      shell: pwsh
    - run: Scripts/dump-data.sh $GITHUB_WORKSPACE/data.json
