name: strategy-and-outputs

on:
  push:
    branches:
      - strategy-and-outputs

jobs:
  one:
    runs-on: ${{ matrix.os }}
    outputs:
      myvar: ${{ steps.step1.outputs.myvar }}    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - id: step1
      run: echo "::set-output name=myvar::${{ matrix.os }}"
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
    - run: echo ${{ needs.one.outputs.myvar }}
    - run: echo ${{ toJson(needs.one.outputs.myvar) }}
    - run: echo ${{ toJson(needs.one.outputs) }}