name: strategy-and-outputs

on:
  push:
    branches:
      - strategy-and-outputs

jobs:
  zero:
    runs-on: ubuntu-latest
    outputs:
      myvar: ${{ steps.step0.outputs.myvar }}
    steps:
    - id: step0
      run: echo "::set-output name=myvar::zero"
  one:
    runs-on: ubuntu-latest
    needs: zero
    outputs:
      myothervar: ${{ steps.step1.outputs.myothervar }}    
    strategy:
      matrix:
        os: [linux, windows]
    steps:
    - id: step1
      run: echo "::set-output name=myothervar::${{ matrix.os }}"
  two:
    runs-on: ubuntu-latest
    needs: [zero, one]
    steps:
    - run: echo ${{needs.zero.outputs.myvar}} ${{needs.one.outputs.myothervar}}
